//export mode an javascript object
module.exports = {
  getSRN: 'Serial number',
  getVER: 'Firmware version',
  getTYP: 'Device type',
  getCNA: 'Device name',
  getALM: 'Alarm',
  getCDE: '',
  getCDF: '',
  getAB: 'Valve',
  getCS1: 'Capacity exchanger resin 1',
  getCYN: 'Current program number',
  getCYT: 'Duration of running program [mm:ss]',
  getDGW: 'Gateway',
  getDWF: 'Average daily water consumption',
  getFCO: 'Iron content',
  getDEN: '',
  getFSL: '',
  getIDS: '',
  getLDF: '',
  getMTF: '',
  getOHF: '',
  getYHF: '',
  getIPA: 'IP address',
  getLAR: 'Last Regeneration',
  getCOF: 'Past cumulative water usage',
  getUNI: '',
  getLNG: '',
  getBLT: '',
  getDMA: '',
  getCNO: '',
  getFIR: 'Firmware name',
  getFLO: 'Current flow',
  getPRS: 'Water pressure',
  getPST: 'Pressure sensor installed',
  getRDO: 'Regenerant dosage',
  getCEL: 'Water temperature',
  getCES: '',
  getCND: '',
  getCNS: '',
  getDAT: '',
  getINR: '',
  getLAN: '',
  getLWT: '',
  getNOR: '',
  getPRF: '',
  getPRN: '',
  getBSI: '',
  getAVO: '',
  getVOL: '',
  getBSA: '',
  getFLL: '',
  getEXI: '',
  getAWY: '',
  getSRV: '',
  getCEO: '',
  getDBD: '',
  getDBT: '',
  getDST: '',
  getDCM: '',
  getDOM: '',
  getDPL: '',
  getDTC: '',
  getDPH: '',
  getRES: 'Remaining capacity',
  getRG1: 'Regeneration running 1',
  getMEX: '',
  getTPA: '',
  getRPD: 'Regeneration every x days',
  getRPW: 'Regeneration every xth day of week',
  getRTH: 'Regeneration time (hour)',
  getRTI: 'Total regeneration time [hh:mm]',
  getBOX: '',
  getRTM: 'Regeneration time (minute)',
  getSCR: '',
  getFLG: '',
  getINT: '',
  getIWH: 'Water hardness',
  getMAC: 'Mac address',
  getMAN: 'Manufacturer',
  getNOT: '',
  getOWH: 'Soft water hardness',
  getPA1: '',
  getPA2: '',
  getPA3: '',
  getPA4: '',
  getPA5: '',
  getPA6: '',
  getPA7: '',
  getPA8: '',
  getPB1: '',
  getPB2: '',
  getPB3: '',
  getPB4: '',
  getPB5: '',
  getPB6: '',
  getPB7: '',
  getPB8: '',
  getPF1: '',
  getPF2: '',
  getPF3: '',
  getPF4: '',
  getPF5: '',
  getPF6: '',
  getPF7: '',
  getPF8: '',
  getPM1: '',
  getPM2: '',
  getPM3: '',
  getPM4: '',
  getPM5: '',
  getPM6: '',
  getPM7: '',
  getPM8: '',
  getPN1: '',
  getPN2: '',
  getPN3: '',
  getPN4: '',
  getPN5: '',
  getPN6: '',
  getPN7: '',
  getPN8: '',
  getPR1: '',
  getPR2: '',
  getPR3: '',
  getPR4: '',
  getPR5: '',
  getPR6: '',
  getPR7: '',
  getPR8: '',
  getPT1: '',
  getPT2: '',
  getPT3: '',
  getPT4: '',
  getPT5: '',
  getPT6: '',
  getPT7: '',
  getPT8: '',
  getPV1: '',
  getPV2: '',
  getPV3: '',
  getPV4: '',
  getPV5: '',
  getPV6: '',
  getPV7: '',
  getPV8: '',
  getPW1: '',
  getPW2: '',
  getPW3: '',
  getPW4: '',
  getPW5: '',
  getPW6: '',
  getPW7: '',
  getPW8: '',
  getSIR: '',
  getSLE: '',
  getSLF: '',
  getSLO: '',
  getSLP: '',
  getSLT: '',
  getSLV: '',
  getSRE: '',
  getSS1: 'Salt supply 1',
  getHUM: '',
  getBUP: '',
  getSTA: 'Name of current program',
  getSV1: 'Amount of salt in the container 1',
  getGLE: '',
};
