//export mode an javascript object
module.exports = {
  getSRN: 'Serial number',
  getVER: 'Firmware version',
  getTYP: 'Device type',
  getCNA: 'Device name',
  getALM: 'Alarm',
  getCDE: '',
  getCS1: 'Capacity exchanger resin 1',
  getCS2: 'Capacity exchanger resin 2',
  getCS3: 'Capacity exchanger resin 3',
  getCYN: 'Current program number',
  getCYT: 'Duration of running program [mm:ss]',
  getDEN: '',
  getDGW: 'Gateway',
  getDWF: 'Average daily water consumption',
  getFCO: 'Iron content',
  getFIR: 'Firmware name',
  getFLO: 'Current flow',
  getHED: 'Holiday start day',
  getHEM: 'Holiday start month',
  getHEY: 'Holiday start year',
  getHSD: 'Holiday end day',
  getHSM: 'Holiday end month',
  getHSY: 'Holiday end year',
  getIPH: '',
  getIWH: 'Water hardness',
  getMAC: 'Mac address',
  getMAN: 'Manufacturer',
  getNOT: 'Alert',
  getOWH: 'Soft water hardness',
  getPA1: '',
  getPA2: '',
  getPA3: '',
  getPRS: 'Water pressure',
  getPST: 'Pressure sensor installed',
  getRDO: 'Regenerant dosage',
  getRES: 'Remaining capacity',
  getRG1: 'Regeneration running 1',
  getRG2: 'Regeneration running 2',
  getRG3: 'Regeneration running 3',
  getRPD: 'Regeneration every x days',
  getRPW: 'Regeneration every xth day of week',
  getRTH: 'Regeneration time (hour)',
  getRTI: 'Total regeneration time [hh:mm]',
  getRTM: 'Regeneration time (minute)',
  getSCR: 'Type',
  getSRE: 'Service regenerations',
  getSS1: 'Salt supply 1',
  getSS2: 'Salt supply 2',
  getSS3: 'Salt supply 3',
  getSTA: 'Name of current program',
  getSV1: 'Amount of salt in the container 1',
  getSV2: 'Amount of salt in the container 2',
  getSV3: 'Amount of salt in the container 3',
  getTOR: 'Total regeneration priors',
  getVAC: '',
  getVS1: '',
  getVS2: '',
  getVS3: '',
  getWHU: 'Unit of water hardness',
  setSIR: 'Regenerate now',
  setSDR: 'Regenerate later',
  setSMR: 'Multi regenerate',
  getMOF: 'Consumption Monday',
  getTUF: 'Consumption Tuesday',
  getWEF: 'Consumption Wednesday',
  getTHF: 'Consumption Thursday',
  getFRF: 'Consumption Friday',
  getSAF: 'Consumption Saturday',
  getSUF: 'Consumption Sunday',
  getTOF: 'Consumption today',
  getYEF: 'Consumption yesterday',
  getCWF: 'Consumption current week',
  getLWF: 'Consumption last week',
  getCMF: 'Consumption current month',
  getLMF: 'Consumption last month',
  getCOF: 'Consumption complete',
  getUWF: 'Consumption untreated',
  getTFO: 'Consumption peak level',
};
